# Generated by Django 4.2.8 on 2024-01-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='img',
            field=models.ImageField(default='null', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
