# Generated by Django 4.2.8 on 2024-02-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_program_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
