# Generated by Django 4.2.8 on 2024-01-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='partici_id',
            new_name='participant_id',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='partici_ph',
            new_name='participant_ph',
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
